name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test-vs-build:
    runs-on: windows-2019
    outputs:
      hello: 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: cmake -G "Visual Studio 16 2019" -A Win32 -S .
      - run: cmake --build . --config Release
      - run: .\Release\hello-cmake.exe
      - uses: actions/upload-artifact@v4
        with:
          path: Release\hello-cmake.exe

